# Основные настройки
api:
  openai_api_key: "your-api-key-here"  # Ключ API OpenAI
  chat_gpt_model: "gpt-4o-mini"  # Модель для рерайта текста

# Настройки аккаунтов Telegram
telegram:
  session_directory: "accounts/"  # Папка с session-файлами аккаунтов
  proxy:
    enabled: false  # Использовать прокси (true/false)
    file: "proxy.txt"  # Файл с прокси в формате IP:Port:Username:Password

# Настройки клонирования
cloning:
  mode: "history"  # Режим работы: history (по истории) или live (в реальном времени)
  posts_to_clone: 5  # Последних постов для клонирования (только для history)
  source_channels_file: "Источники.txt"  # Файл с каналами-донорами
  target_channels_file: "Цель.txt"  # Файл с целевыми каналами и аккаунтами

# Настройки уникализации
uniqueness:
  text:
    rewrite: true  # Использовать рерайт через ChatGPT
    symbol_masking: true  # Маскировка RU-EN символов
    replacements_file: "Замены.txt"  # Файл с заменами слов
    prompt_file: "prompt.txt" # Файл с промптом
  image:
    crop: [1, 4]  # Кадрирование (в пикселях)
    brightness: [1, 7]  # Изменение яркости (%)
    contrast: [1, 7]  # Изменение контраста (%)
    rotation: true  # Изменение градуса поворота
    metadata: "replace"  # Удаление или замена метаданных
    filters: true  # Применение скрытых фильтров
  video:
    hash_change: true  # Изменение хеша видео
    watermark: true  # Невидимые элементы (сетка и т. д.)
    frame_rate_variation: true  # Незначительное изменение FPS
    audio_speed: [2, 4]  # Изменение скорости аудио (%)
    metadata: "replace"  # или "remove"

# Настройки задержек
timeouts:
  join_delay: [5, 15]  # Задержка перед подпиской на канал
  post_delay: [5, 15]  # Задержка перед отправкой сообщений (в секундах)
  flood_wait_limit: 300  # Максимальное время ожидания при флуд-ограничении (в секундах)

# Логирование
logging:
  log_file: "logs/app.log"  # Основной лог-файл
  error_log_file: "logs/errors.log"  # Файл логирования ошибок
